#include "selftest.h"
#include "mainwindow.h"
#include <QtWidgets>
#include <private/qzipreader_p.h>
#include <private/qzipwriter_p.h>
#include <cmath>
#include <stdexcept>

namespace {
QString tracePath;
void require(bool value,const char *message){QFile trace(tracePath);if(trace.open(QIODevice::Append)){trace.write(value?"PASS ":"FAIL ");trace.write(message);trace.write("\n");}if(!value)throw std::runtime_error(message);}
void mouse(Canvas *canvas,QEvent::Type type,QPointF position,Qt::MouseButton button,Qt::MouseButtons buttons,Qt::KeyboardModifiers modifiers=Qt::NoModifier){QMouseEvent event(type,position,button,buttons,modifiers);QApplication::sendEvent(canvas,&event);}
void drag(Canvas *canvas,QPointF a,QPointF b){mouse(canvas,QEvent::MouseButtonPress,canvas->toView(a),Qt::LeftButton,Qt::LeftButton);mouse(canvas,QEvent::MouseMove,canvas->toView(b),Qt::NoButton,Qt::LeftButton);mouse(canvas,QEvent::MouseButtonRelease,canvas->toView(b),Qt::LeftButton,Qt::NoButton);}
void click(Canvas *canvas,QPointF point,Qt::KeyboardModifiers modifiers=Qt::NoModifier){mouse(canvas,QEvent::MouseButtonPress,canvas->toView(point),Qt::LeftButton,Qt::LeftButton,modifiers);mouse(canvas,QEvent::MouseButtonRelease,canvas->toView(point),Qt::LeftButton,Qt::NoButton,modifiers);}
}

int runSelfTests(const QString &outputDirectory){
    try{
        if(QGuiApplication::platformName()=="offscreen")QApplication::setStyle("Fusion");
        QFontDatabase::addApplicationFont(qEnvironmentVariable("WINDIR")+"/Fonts/segoeui.ttf");
        QDir().mkpath(outputDirectory);QDir out(outputDirectory);
        QSettings::setDefaultFormat(QSettings::IniFormat);QSettings::setPath(QSettings::IniFormat,QSettings::UserScope,out.filePath("settings"));QSettings().clear();
        tracePath=out.filePath("trace.txt");{QFile trace(tracePath);trace.open(QIODevice::WriteOnly);}
        QTimer watchdog;watchdog.setSingleShot(true);watchdog.setInterval(12000);QObject::connect(&watchdog,&QTimer::timeout,[]{QFile trace(tracePath);trace.open(QIODevice::Append);trace.write("TIMEOUT\n");for(auto *widget:QApplication::topLevelWidgets()){trace.write(widget->metaObject()->className());trace.write(" ");trace.write(widget->windowTitle().toUtf8());trace.write("\n");}trace.close();std::exit(2);});watchdog.start();
        MainWindow window;window.show();QApplication::processEvents();
        require(QCoreApplication::applicationName()==QStringLiteral("TechDraw")&&QApplication::applicationDisplayName()==QStringLiteral("TechDraw")&&window.windowTitle().contains(QStringLiteral("TechDraw")),"application branding was not changed to TechDraw");
        Canvas *canvas=window.canvas();
        auto *mainToolbar=window.findChild<QToolBar*>("mainToolbar");auto *toolsToolbar=window.findChild<QToolBar*>("toolsToolbar");auto *fileMenu=window.findChild<QMenu*>("fileMenu");auto *editMenu=window.findChild<QMenu*>("editMenu");auto *viewMenu=window.findChild<QMenu*>("viewMenu");auto *toolsMenu=window.findChild<QMenu*>("toolsMenu");
        require(mainToolbar&&toolsToolbar&&mainToolbar->toolButtonStyle()==Qt::ToolButtonIconOnly&&toolsToolbar->toolButtonStyle()==Qt::ToolButtonIconOnly,"toolbars must show icons only");
        auto *mainToolbarToggle=window.findChild<QAction*>("mainToolbarToggle");auto *toolsToolbarToggle=window.findChild<QAction*>("toolsToolbarToggle");
        require(fileMenu&&editMenu&&viewMenu&&toolsMenu&&mainToolbarToggle&&toolsToolbarToggle&&viewMenu->actions().contains(mainToolbarToggle)&&viewMenu->actions().contains(toolsToolbarToggle),"menus or toolbar visibility actions are missing");
        mainToolbarToggle->trigger();QApplication::processEvents();require(!mainToolbar->isVisible(),"main toolbar could not be hidden through View menu");mainToolbarToggle->trigger();
        toolsToolbarToggle->trigger();QApplication::processEvents();require(!toolsToolbar->isVisible(),"tools toolbar could not be hidden through View menu");toolsToolbarToggle->trigger();QApplication::processEvents();
        auto *newMenuAction=window.findChild<QAction*>("newAction");auto *openMenuAction=window.findChild<QAction*>("openAction");auto *saveMenuAction=window.findChild<QAction*>("saveAction");auto *undoMenuAction=window.findChild<QAction*>("undoAction");auto *redoMenuAction=window.findChild<QAction*>("redoAction");auto *widthMenuAction=window.findChild<QAction*>("strokeWidthAction");auto *frontMenuAction=window.findChild<QAction*>("frontColorAction");auto *backMenuAction=window.findChild<QAction*>("backColorAction");auto *swapMenuAction=window.findChild<QAction*>("swapColorsAction");
        require(newMenuAction&&openMenuAction&&saveMenuAction&&undoMenuAction&&redoMenuAction&&widthMenuAction&&frontMenuAction&&backMenuAction&&swapMenuAction&&fileMenu->actions().contains(newMenuAction)&&fileMenu->actions().contains(openMenuAction)&&fileMenu->actions().contains(saveMenuAction)&&editMenu->actions().contains(undoMenuAction)&&editMenu->actions().contains(redoMenuAction)&&toolsMenu->actions().contains(widthMenuAction)&&toolsMenu->actions().contains(frontMenuAction)&&toolsMenu->actions().contains(backMenuAction)&&toolsMenu->actions().contains(swapMenuAction),"main toolbar commands are not all available through menus");
        for(int i=0;i<5;++i){auto *toolAction=window.findChild<QAction*>(QString("tool%1").arg(i));require(toolAction&&toolsMenu->actions().contains(toolAction),"drawing tool is missing from Tools menu");}
        auto *frontButton=window.findChild<QPushButton*>("frontColor");auto *backButton=window.findChild<QPushButton*>("backColor");
        require(frontButton&&backButton&&frontButton->text().isEmpty()&&backButton->text().isEmpty()&&!frontButton->toolTip().isEmpty()&&!backButton->toolTip().isEmpty(),"color buttons must use tooltips instead of labels");
        auto *fitButton=window.findChild<QToolButton*>("fitButton");auto *actualButton=window.findChild<QToolButton*>("actualSizeButton");
        require(fitButton&&actualButton&&fitButton->toolButtonStyle()==Qt::ToolButtonIconOnly&&actualButton->toolButtonStyle()==Qt::ToolButtonIconOnly&&!fitButton->toolTip().isEmpty()&&!actualButton->toolTip().isEmpty(),"status buttons must show icons and tooltips");
        auto *rayStep=window.findChild<QDoubleSpinBox*>("rayStep");auto *rayGap=window.findChild<QSpinBox*>("rayGap");auto *rayStartOpacity=window.findChild<QSpinBox*>("rayStartOpacity");auto *rayEndOpacity=window.findChild<QSpinBox*>("rayEndOpacity");auto *rayFadeLength=window.findChild<QSpinBox*>("rayFadeLength");auto *rayPattern=window.findChild<QComboBox*>("rayPattern");auto *rayWidth=window.findChild<QDoubleSpinBox*>("rayWidth");auto *rayAngleOffset=window.findChild<QDoubleSpinBox*>("rayAngleOffset");
        require(rayStep&&rayGap&&rayStartOpacity&&rayEndOpacity&&rayFadeLength&&rayPattern&&rayWidth&&rayAngleOffset&&rayStep->maximum()==30.0&&rayStep->value()==10.0&&rayGap->value()==12&&rayStartOpacity->value()==10&&rayEndOpacity->value()==70&&rayFadeLength->value()==50&&rayPattern->count()==4&&rayWidth->value()==1&&rayAngleOffset->value()==0,"perspective ray appearance controls are missing or invalid");
        auto *vanishingPointSettings=window.findChild<QGroupBox*>("vanishingPointSettings");auto *vanishingPointsList=window.findChild<QGroupBox*>("vanishingPointsList");auto *selectedPointSettings=window.findChild<QGroupBox*>("selectedVanishingPointSettings");auto *pointsListControl=window.findChild<QListWidget*>("vanishingPointsListControl");auto *addPoint=window.findChild<QPushButton*>("addVanishingPoint");auto *removePoint=window.findChild<QPushButton*>("removeVanishingPoint");auto *gridColor=window.findChild<QPushButton*>("gridColor");auto *savePerspectiveDefaults=window.findChild<QPushButton*>("savePerspectiveDefaults");auto *resetPerspectiveDefaults=window.findChild<QPushButton*>("resetPerspectiveDefaults");
        require(vanishingPointSettings&&vanishingPointSettings->title()==QStringLiteral("Настройки точек схода")&&vanishingPointsList&&selectedPointSettings&&pointsListControl&&addPoint&&removePoint&&gridColor&&savePerspectiveDefaults&&resetPerspectiveDefaults&&vanishingPointSettings->isAncestorOf(rayStep)&&vanishingPointSettings->isAncestorOf(rayGap)&&vanishingPointSettings->isAncestorOf(rayStartOpacity)&&vanishingPointSettings->isAncestorOf(rayEndOpacity)&&vanishingPointSettings->isAncestorOf(rayFadeLength)&&vanishingPointSettings->isAncestorOf(savePerspectiveDefaults)&&vanishingPointSettings->isAncestorOf(resetPerspectiveDefaults)&&vanishingPointsList->isAncestorOf(selectedPointSettings)&&selectedPointSettings->isAncestorOf(gridColor),"perspective panel must separate common settings, point list, and selected point properties");
        auto *horizonSettings=window.findChild<QGroupBox*>("horizonSettings");auto *horizonColor=window.findChild<QPushButton*>("horizonColor");auto *horizonOpacity=window.findChild<QSpinBox*>("horizonOpacity");auto *horizonWidth=window.findChild<QDoubleSpinBox*>("horizonWidth");auto *horizonLocked=window.findChild<QCheckBox*>("horizonLocked");auto *selectedPointLocked=window.findChild<QCheckBox*>("selectedPointLocked");
        require(horizonSettings&&horizonColor&&horizonOpacity&&horizonWidth&&horizonLocked&&selectedPointLocked&&horizonSettings->isAncestorOf(horizonColor)&&horizonSettings->isAncestorOf(horizonOpacity)&&horizonSettings->isAncestorOf(horizonWidth)&&horizonSettings->isAncestorOf(horizonLocked)&&selectedPointSettings->isAncestorOf(selectedPointLocked)&&horizonOpacity->value()==70&&horizonWidth->value()==1.0&&!horizonLocked->isChecked()&&!selectedPointLocked->isChecked(),"horizon or vanishing-point lock controls are missing, misplaced, or invalid");
        auto *perspectivePanel=qobject_cast<QWidget*>(horizonSettings->parentWidget());auto *perspectiveLayout=perspectivePanel?qobject_cast<QVBoxLayout*>(perspectivePanel->layout()):nullptr;
        require(perspectiveLayout&&perspectiveLayout->indexOf(horizonSettings)<perspectiveLayout->indexOf(vanishingPointSettings)&&perspectiveLayout->indexOf(vanishingPointSettings)<perspectiveLayout->indexOf(vanishingPointsList),"perspective blocks must be ordered as horizon, point settings, and point list");
        require(pointsListControl->count()==1&&canvas->state().vanishingPoints.size()==1,"initial vanishing point list is invalid");
        const QString firstPointId=canvas->state().vanishingPoints[0].id;addPoint->click();require(pointsListControl->count()==2&&canvas->state().vanishingPoints.size()==2&&canvas->selectedPointIndex()==1&&canvas->state().vanishingPoints[1].id!=firstPointId,"adding and selecting a second vanishing point failed");
        removePoint->click();require(canvas->state().vanishingPoints.size()==1,"removing a vanishing point failed");canvas->undoStack()->undo();require(canvas->state().vanishingPoints.size()==2,"vanishing point deletion must be undoable");canvas->undoStack()->redo();require(canvas->state().vanishingPoints.size()==1,"vanishing point deletion redo failed");canvas->undoStack()->setClean();
        auto *pointX=window.findChild<QDoubleSpinBox*>("vanishingPointX");auto *pointY=window.findChild<QDoubleSpinBox*>("vanishingPointY");auto *pointUnits=window.findChild<QComboBox*>("vanishingPointUnits");auto *horizonPosition=window.findChild<QDoubleSpinBox*>("horizonPosition");auto *horizonUnits=window.findChild<QComboBox*>("horizonUnits");auto *pointAttachment=window.findChild<QComboBox*>("vanishingPointAttachment");auto *canvasPosition=window.findChild<QLabel*>("canvasPosition");
        require(pointX&&pointY&&pointUnits&&horizonPosition&&horizonUnits&&pointAttachment&&canvasPosition&&pointUnits->currentIndex()==0&&horizonUnits->currentIndex()==0&&std::abs(pointX->value()-15.0)<0.01&&std::abs(pointY->value()-11.29)<0.02,"centered percentage coordinate controls are missing or incorrect");
        mouse(canvas,QEvent::MouseMove,canvas->toView(QPointF(600,260)),Qt::NoButton,Qt::NoButton);require(!canvas->rulerPercent()&&canvasPosition->text()==QStringLiteral("X: 100 px   Y: 50 px"),"canvas rulers must default to centered pixels while point fields use percent");
        const QPointF beforeUnitChange=canvas->state().vanishingPoints[0].position;pointUnits->setCurrentIndex(1);require(horizonUnits->currentIndex()==1&&pointX->value()==150&&pointY->value()==70&&horizonPosition->value()==70&&canvas->state().vanishingPoints[0].position==beforeUnitChange,"unit switching must preserve geometry and synchronize coordinate controls");
        require(!canvas->rulerPercent(),"changing vanishing point units must not change ruler units");
        auto *settingsAction=window.findChild<QAction*>("settingsAction");bool settingsDialogChecked=false;QTimer::singleShot(0,&window,[&]{auto *dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());auto *tabs=dialog?dialog->findChild<QTabWidget*>("settingsTabs"):nullptr;auto *rulerUnits=dialog?dialog->findChild<QComboBox*>("rulerUnits"):nullptr;settingsDialogChecked=tabs&&tabs->count()==3&&tabs->tabText(0)==QStringLiteral("Вид")&&tabs->tabText(1)==QStringLiteral("Система")&&tabs->tabText(2)==QStringLiteral("Файлы")&&rulerUnits&&rulerUnits->currentIndex()==0;if(rulerUnits)rulerUnits->setCurrentIndex(1);if(dialog)dialog->accept();});require(settingsAction,"settings action is missing");settingsAction->trigger();
        require(settingsDialogChecked&&canvas->rulerPercent()&&QSettings().value("view/rulers/percent").toBool()&&pointUnits->currentIndex()==1,"settings dialog did not persist independent ruler units");
        pointX->setValue(-300);require(canvas->state().vanishingPoints[0].position==QPointF(200,240),"numeric X coordinate did not update the attached point");pointAttachment->setCurrentIndex(0);pointY->setValue(100);require(canvas->state().vanishingPoints[0].position==QPointF(200,210)&&canvas->state().vanishingPoints[0].attachmentType.isEmpty(),"free point numeric Y coordinate or attachment state is incorrect");
        horizonPosition->setValue(50);require(canvas->state().horizonY==260&&canvas->state().vanishingPoints[0].position==QPointF(200,210),"numeric horizon position must not move a free point");canvas->undoStack()->setClean();
        require(!savePerspectiveDefaults->isEnabled(),"unchanged factory perspective defaults must not be saveable");
        auto *newAction=window.findChild<QAction*>("newAction");require(newAction,"new canvas action missing");
        QTimer::singleShot(0,&window,[]{auto *dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());if(!dialog)return;auto *width=dialog->findChild<QSpinBox*>("newCanvasWidth");auto *height=dialog->findChild<QSpinBox*>("newCanvasHeight");if(width&&height){width->setValue(640);height->setValue(480);dialog->accept();}});newAction->trigger();
        require(window.canvas()->state().image.size()==QSize(640,480)&&QSettings().value("canvas/newWidth").toInt()==640&&QSettings().value("canvas/newHeight").toInt()==480,"new canvas size was not remembered after creation");
        MainWindow rememberedSizeWindow;bool rememberedSizeShown=false;auto *rememberedNewAction=rememberedSizeWindow.findChild<QAction*>("newAction");
        QTimer::singleShot(0,&rememberedSizeWindow,[&]{auto *dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());if(!dialog)return;auto *width=dialog->findChild<QSpinBox*>("newCanvasWidth");auto *height=dialog->findChild<QSpinBox*>("newCanvasHeight");rememberedSizeShown=width&&height&&width->value()==640&&height->value()==480;if(width&&height){width->setValue(800);height->setValue(600);}dialog->reject();});rememberedNewAction->trigger();
        require(rememberedSizeShown&&QSettings().value("canvas/newWidth").toInt()==640&&QSettings().value("canvas/newHeight").toInt()==480,"new canvas dialog did not restore size or cancel changed it");rememberedSizeWindow.close();
        canvas->undoStack()->setClean();const int beforeAppearanceChange=canvas->undoStack()->count();
        rayStep->setValue(7.5);rayGap->setValue(20);rayStartOpacity->setValue(15);rayEndOpacity->setValue(80);rayFadeLength->setValue(60);rayPattern->setCurrentIndex(1);rayWidth->setValue(2.5);rayAngleOffset->setValue(12);
        require(canvas->state().rayStepDegrees==7.5&&canvas->state().rayGap==20&&canvas->state().rayStartOpacity==15&&canvas->state().rayEndOpacity==80&&canvas->state().rayFadeLength==60&&canvas->state().rayPattern==1&&canvas->state().rayWidth==2.5&&canvas->state().rayAngleOffset==12,"perspective controls did not update the document");
        require(canvas->undoStack()->count()==beforeAppearanceChange&&canvas->undoStack()->isClean(),"perspective appearance must not enter project history or dirty the document");
        horizonOpacity->setValue(35);horizonWidth->setValue(3.5);QSettings().setValue("perspective/view/horizonColor",QStringLiteral("#d43b3b"));canvas->setHorizonColor(QColor("#d43b3b"));
        require(canvas->state().horizonColor==QColor("#d43b3b")&&canvas->state().horizonOpacity==35&&canvas->state().horizonWidth==3.5&&canvas->undoStack()->count()==beforeAppearanceChange&&canvas->undoStack()->isClean(),"horizon appearance must be independent and remain outside project history");
        require(savePerspectiveDefaults->isEnabled(),"changed perspective defaults must enable saving");
        savePerspectiveDefaults->click();QSettings savedDefaults;
        require(savedDefaults.value("perspective/common/rayStepDegrees").toDouble()==7.5&&savedDefaults.value("perspective/common/rayGap").toInt()==20&&savedDefaults.value("perspective/common/rayStartOpacity").toInt()==15&&savedDefaults.value("perspective/common/rayEndOpacity").toInt()==80&&savedDefaults.value("perspective/common/rayFadeLength").toInt()==60&&savedDefaults.value("perspective/common/rayPattern").toInt()==1,"save common perspective settings did not persist all six values");
        require(!savePerspectiveDefaults->isEnabled(),"saving perspective defaults must disable the save button");
        rayGap->setValue(21);require(savePerspectiveDefaults->isEnabled(),"changing one saved perspective value must enable the save button");rayGap->setValue(20);require(!savePerspectiveDefaults->isEnabled(),"restoring saved perspective values must disable the save button");
        MainWindow defaultsWindow;auto *savedRayStep=defaultsWindow.findChild<QDoubleSpinBox*>("rayStep");auto *savedRayGap=defaultsWindow.findChild<QSpinBox*>("rayGap");auto *savedStartOpacity=defaultsWindow.findChild<QSpinBox*>("rayStartOpacity");auto *savedEndOpacity=defaultsWindow.findChild<QSpinBox*>("rayEndOpacity");auto *savedFadeLength=defaultsWindow.findChild<QSpinBox*>("rayFadeLength");auto *savedPattern=defaultsWindow.findChild<QComboBox*>("rayPattern");auto *resetSavedDefaults=defaultsWindow.findChild<QPushButton*>("resetPerspectiveDefaults");
        auto *saveSavedDefaults=defaultsWindow.findChild<QPushButton*>("savePerspectiveDefaults");require(savedRayStep&&savedRayGap&&savedStartOpacity&&savedEndOpacity&&savedFadeLength&&savedPattern&&saveSavedDefaults&&resetSavedDefaults&&savedRayStep->value()==7.5&&savedRayGap->value()==20&&savedStartOpacity->value()==15&&savedEndOpacity->value()==80&&savedFadeLength->value()==60&&savedPattern->currentIndex()==1&&!saveSavedDefaults->isEnabled(),"saved common perspective settings were not applied to a new document");require(defaultsWindow.canvas()->state().horizonColor==QColor("#d43b3b")&&defaultsWindow.canvas()->state().horizonOpacity==35&&defaultsWindow.canvas()->state().horizonWidth==3.5&&defaultsWindow.canvas()->state().rayWidth==2.5&&defaultsWindow.canvas()->state().rayAngleOffset==12,"application display settings did not persist between windows");
        const int beforeReset=defaultsWindow.canvas()->undoStack()->count();resetSavedDefaults->click();require(defaultsWindow.canvas()->state().rayStepDegrees==10&&defaultsWindow.canvas()->state().rayGap==12&&defaultsWindow.canvas()->state().rayStartOpacity==10&&defaultsWindow.canvas()->state().rayEndOpacity==70&&defaultsWindow.canvas()->state().rayFadeLength==50&&defaultsWindow.canvas()->state().rayPattern==0&&defaultsWindow.canvas()->undoStack()->count()==beforeReset&&!QSettings().contains("perspective/common/rayStepDegrees")&&!saveSavedDefaults->isEnabled(),"reset common perspective settings did not restore factory values outside project history");defaultsWindow.close();
        QSettings().remove("perspective/view");
        DrawingState initial;initial.image=QImage(1000,620,QImage::Format_ARGB32_Premultiplied);initial.image.fill(Qt::white);initial.horizonY=240;initial.vanishingPoints.append({QStringLiteral("vp-1"),QPointF(650,240),QString(),QString()});
        auto *horizonVisible=window.findChild<QCheckBox*>("horizonVisible");auto *axesVisible=window.findChild<QCheckBox*>("axesVisible");auto *markersVisible=window.findChild<QCheckBox*>("markersVisible");auto *symmetricPoints=window.findChild<QCheckBox*>("symmetricPoints");require(horizonVisible&&axesVisible&&markersVisible&&symmetricPoints,"perspective visibility and symmetry controls are missing");
        DrawingState pair=initial;pair.vanishingPoints[0].attachmentType=QStringLiteral("construction");pair.vanishingPoints[0].attachmentTargetId=QStringLiteral("horizon");pair.vanishingPoints.append({QStringLiteral("vp-2"),QPointF(350,240),QStringLiteral("construction"),QStringLiteral("horizon")});canvas->setDocument(pair);canvas->setSymmetricPoints(true);canvas->selectPoint(0);canvas->setSelectedPointPosition(QPointF(720,240));require(canvas->state().vanishingPoints[1].position==QPointF(280,240),"symmetric pair movement failed");
        Canvas rulerCanvas;rulerCanvas.resize(500,400);rulerCanvas.setDocument(initial);rulerCanvas.setGridVisible(false);rulerCanvas.fit();QEvent leave(QEvent::Leave);QApplication::sendEvent(&rulerCanvas,&leave);QImage rulersOnly(rulerCanvas.size(),QImage::Format_ARGB32_Premultiplied);rulersOnly.fill(Qt::transparent);rulerCanvas.render(&rulersOnly);const QColor rulerBackground("#f4f5f7");int topRuler=0,bottomRuler=0,leftRuler=0,rightRuler=0;for(int x=0;x<500;++x){if(rulersOnly.pixelColor(x,10)==rulerBackground)++topRuler;if(rulersOnly.pixelColor(x,390)==rulerBackground)++bottomRuler;}for(int y=28;y<372;++y){if(rulersOnly.pixelColor(10,y)==rulerBackground)++leftRuler;if(rulersOnly.pixelColor(490,y)==rulerBackground)++rightRuler;}require(topRuler>250&&bottomRuler>250&&leftRuler>170&&rightRuler>170,"four fixed viewport rulers were not rendered");
        const QImage rulerPixels=rulerCanvas.state().image;mouse(&rulerCanvas,QEvent::MouseMove,QPointF(250,200),Qt::NoButton,Qt::NoButton);QImage cursorProjection(rulerCanvas.size(),QImage::Format_ARGB32_Premultiplied);cursorProjection.fill(Qt::transparent);rulerCanvas.render(&cursorProjection);int changedPixels=0;for(int y=0;y<cursorProjection.height();++y)if(cursorProjection.pixelColor(250,y)!=rulersOnly.pixelColor(250,y))++changedPixels;for(int x=0;x<cursorProjection.width();++x)if(cursorProjection.pixelColor(x,200)!=rulersOnly.pixelColor(x,200))++changedPixels;require(changedPixels>20&&rulerCanvas.state().image==rulerPixels&&rulerCanvas.undoStack()->isClean(),"cursor projection must reach all rulers without editing the document");
        DrawingState lockState=initial;lockState.gridVisible=true;lockState.vanishingPoints[0].attachmentType=QStringLiteral("construction");lockState.vanishingPoints[0].attachmentTargetId=QStringLiteral("horizon");Canvas lockCanvas;lockCanvas.resize(700,500);lockCanvas.setDocument(lockState);lockCanvas.fit();lockCanvas.setTool(Canvas::Perspective);lockCanvas.setSelectedPointLocked(true);require(lockCanvas.state().vanishingPoints[0].locked,"vanishing point lock was not enabled");lockCanvas.undoStack()->undo();require(!lockCanvas.state().vanishingPoints[0].locked,"vanishing point lock undo failed");lockCanvas.undoStack()->redo();lockCanvas.setHorizonLocked(true);require(lockCanvas.state().horizonLocked,"horizon lock was not enabled");lockCanvas.undoStack()->undo();require(!lockCanvas.state().horizonLocked,"horizon lock undo failed");lockCanvas.undoStack()->redo();
        const QPointF fixedPoint=lockCanvas.state().vanishingPoints[0].position;const double fixedHorizon=lockCanvas.state().horizonY;drag(&lockCanvas,fixedPoint,fixedPoint+QPointF(80,40));drag(&lockCanvas,QPointF(100,fixedHorizon),QPointF(100,fixedHorizon+60));require(lockCanvas.state().vanishingPoints[0].position==fixedPoint&&lockCanvas.state().horizonY==fixedHorizon,"locked perspective objects must ignore direct dragging");lockCanvas.setSelectedPointPosition(fixedPoint+QPointF(40,0));require(lockCanvas.state().vanishingPoints[0].position==fixedPoint+QPointF(40,0),"numeric input must move a locked vanishing point");lockCanvas.setHorizonY(fixedHorizon+30);require(lockCanvas.state().horizonY==fixedHorizon+30&&lockCanvas.state().vanishingPoints[0].position.y()==fixedPoint.y()+30,"numeric horizon movement must remain available and carry an attached locked point");
        canvas->setDocument(initial);canvas->fit();
        require(canvas->undoStack()->isClean(),"initial document must be clean");
        canvas->setStrokeWidth(9);canvas->setFront(QColor("#26364a"));
        drag(canvas,QPointF(120,100),QPointF(280,100));
        require(canvas->state().image.pixelColor(200,100)==QColor("#26364a"),"pencil stroke did not reach image");
        require(!canvas->undoStack()->isClean(),"stroke must make document dirty");
        canvas->undoStack()->undo();require(canvas->state().image==initial.image,"undo must restore pixels");require(canvas->undoStack()->isClean(),"undo back to saved image must be clean");
        canvas->undoStack()->redo();require(canvas->state().image!=initial.image,"redo must restore stroke");
        canvas->setBack(QColor("#e8cf9b"));canvas->setTool(Canvas::Eraser);drag(canvas,QPointF(190,95),QPointF(190,105));require(canvas->state().image.pixelColor(190,100)==QColor("#e8cf9b"),"eraser must use Back");
        canvas->setDocument(initial);canvas->setTool(Canvas::Pencil);canvas->setFront(QColor("#26364a"));canvas->setStrokeWidth(3);
        click(canvas,{100,200});click(canvas,{200,200},Qt::ShiftModifier);click(canvas,{200,260},Qt::ShiftModifier);
        require(canvas->state().image.pixelColor(150,200)==QColor("#26364a")&&canvas->state().image.pixelColor(200,230)==QColor("#26364a"),"shift clicks must create connected segments");
        canvas->undoStack()->undo();require(canvas->state().image.pixelColor(150,200)==QColor("#26364a")&&canvas->state().image.pixelColor(200,230)==QColor(Qt::white),"each connected segment must be separately undoable");canvas->undoStack()->redo();
        click(canvas,{300,300});click(canvas,{390,310},Qt::ShiftModifier|Qt::ControlModifier);
        require(canvas->state().image.pixelColor(350,300)==QColor("#26364a"),"ctrl shift must constrain segment angle");
        canvas->setDocument(initial);canvas->setTool(Canvas::Brush);canvas->setFront(QColor("#6c3f88"));canvas->setStrokeWidth(11);drag(canvas,{110,180},{210,180});
        require(canvas->state().image.pixelColor(160,180)==QColor("#6c3f88"),"brush stroke did not reach image");
        canvas->setBack(QColor("#e8cf9b"));canvas->setTool(Canvas::Eraser);click(canvas,{110,180});click(canvas,{210,180},Qt::ShiftModifier);
        require(canvas->state().image.pixelColor(160,180)==QColor("#e8cf9b"),"eraser straight segment must use Back");
        const int undoIndex=canvas->undoStack()->index();const QImage pixels=canvas->state().image;
        canvas->setZoom(1.7,QPointF(100,150));require(canvas->state().image==pixels&&canvas->undoStack()->index()==undoIndex,"zoom must not edit document");
        QPointF point(100,100);require(QLineF(canvas->toImage(canvas->toView(point)),point).length()<0.001,"view coordinate roundtrip failed");
        canvas->setTool(Canvas::Pan);drag(canvas,QPointF(100,100),QPointF(150,130));require(canvas->state().image==pixels&&canvas->undoStack()->index()==undoIndex,"pan must not edit document");
        canvas->fit();canvas->setGridVisible(true);canvas->setTool(Canvas::Perspective);drag(canvas,QPointF(650,240),QPointF(600,210));require(QLineF(canvas->state().vanishingPoints[0].position,QPointF(600,210)).length()<0.01,"perspective point must move freely away from the horizon");require(canvas->state().image==pixels,"perspective must not alter pixels");
        QApplication::sendEvent(canvas,&leave);QImage freePointView(canvas->size(),QImage::Format_ARGB32_Premultiplied);freePointView.fill(Qt::transparent);canvas->render(&freePointView);const QPointF freePoint=canvas->toView(canvas->state().vanishingPoints[0].position);require(freePointView.pixelColor(qRound(freePoint.x()),qRound(freePoint.y()))==QColor(Qt::white),"free vanishing point must not show the snap indicator");
        drag(canvas,QPointF(600,210),QPointF(550,245));require(canvas->state().vanishingPoints[0].position==QPointF(550,240),"perspective point must snap near the horizon");
        drag(canvas,QPointF(100,240),QPointF(100,300));require(canvas->state().horizonY==300&&canvas->state().vanishingPoints[0].position==QPointF(550,300),"moving the horizon must carry a snapped vanishing point vertically");
        QApplication::sendEvent(canvas,&leave);QImage gridView(canvas->size(),QImage::Format_ARGB32_Premultiplied);gridView.fill(Qt::transparent);canvas->render(&gridView);
        const QPointF snappedPoint=canvas->toView(canvas->state().vanishingPoints[0].position);require(gridView.pixelColor(qRound(snappedPoint.x()),qRound(snappedPoint.y()))==canvas->state().vanishingPoints[0].color,"snapped vanishing point must show its colored center");
        const QRectF paper(canvas->toView(QPointF()),QSizeF(canvas->state().image.size())*canvas->zoom());
        const QPoint outsideHorizon(qRound(paper.right()+12),qRound(canvas->toView(QPointF(0,canvas->state().horizonY)).y()));
        bool horizonOutsideCanvas=false;for(int y=outsideHorizon.y()-2;y<=outsideHorizon.y()+2;++y)for(int x=outsideHorizon.x()-2;x<=outsideHorizon.x()+2;++x)if(gridView.valid(x,y)&&gridView.pixelColor(x,y)!=QColor("#dce0e5"))horizonOutsideCanvas=true;
        require(outsideHorizon.x()<canvas->width()&&horizonOutsideCanvas,"horizon must remain visible outside the canvas");
        canvas->undoStack()->undo();require(canvas->state().horizonY==240&&canvas->state().vanishingPoints[0].position==QPointF(550,240),"horizon undo failed");
        canvas->undoStack()->undo();require(canvas->state().vanishingPoints[0].position==QPointF(600,210),"snapping undo failed");
        canvas->undoStack()->undo();require(canvas->state().vanishingPoints[0].position==QPointF(650,240),"free perspective point undo failed");canvas->undoStack()->redo();
        canvas->undoStack()->undo();require(canvas->undoStack()->canUndo()&&canvas->undoStack()->canRedo(),"history fixture must have undo and redo operations");
        const DrawingHistory savedHistory=canvas->history();
        QString error;const auto projectPath=out.filePath("roundtrip.drw");require(Project::save(projectPath,savedHistory,&error),qPrintable(error));
        DrawingHistory loadedHistory;require(Project::load(projectPath,&loadedHistory,&error),qPrintable(error));
        require(loadedHistory.states.size()==savedHistory.states.size()&&loadedHistory.labels==savedHistory.labels&&loadedHistory.index==savedHistory.index,"DRW history index or labels mismatch");
        Canvas restored;restored.setDocument(loadedHistory,true);const DrawingState restoredCurrent=restored.state();const QString undoLabel=restored.undoStack()->undoText();const QString redoLabel=restored.undoStack()->redoText();
        require(restored.undoStack()->isClean()&&restored.undoStack()->canUndo()&&restored.undoStack()->canRedo()&&!undoLabel.isEmpty()&&!redoLabel.isEmpty(),"restored history must preserve clean index and both directions");
        restored.undoStack()->undo();require(restored.state().vanishingPoints!=restoredCurrent.vanishingPoints||restored.state().gridVisible!=restoredCurrent.gridVisible||restored.state().image!=restoredCurrent.image,"restored undo did not change state");
        restored.undoStack()->redo();require(restored.state().image==restoredCurrent.image&&restored.state().vanishingPoints==restoredCurrent.vanishingPoints&&restored.undoStack()->isClean(),"restored redo did not return to saved state");
        DrawingState loaded;require(Project::load(projectPath,&loaded,&error),qPrintable(error));require(loaded.image==canvas->state().image&&loaded.vanishingPoints==canvas->state().vanishingPoints&&loaded.horizonY==canvas->state().horizonY&&!loaded.gridVisible,"DRW geometry roundtrip mismatch");
        DrawingState styled=initial;styled.gridVisible=true;styled.vanishingPoints[0].position.setY(210);styled.vanishingPoints[0].locked=true;styled.horizonLocked=true;styled.rayStepDegrees=7.5;styled.rayGap=20;styled.rayStartOpacity=15;styled.rayEndOpacity=80;styled.rayFadeLength=60;styled.horizonColor=QColor("#d43b3b");styled.horizonOpacity=100;styled.horizonWidth=3;
        require(Project::save(out.filePath("styled-guides.drw"),styled,&error)&&Project::load(out.filePath("styled-guides.drw"),&loaded,&error),qPrintable(error));
        require(loaded.vanishingPoints[0].position.y()==210&&loaded.vanishingPoints[0].locked&&loaded.horizonY==240&&loaded.horizonLocked&&!loaded.gridVisible&&loaded.vanishingPoints[0].color==QColor("#628ed1")&&loaded.rayStepDegrees==10&&loaded.rayGap==12&&loaded.rayStartOpacity==10&&loaded.rayEndOpacity==70&&loaded.rayFadeLength==50&&loaded.horizonColor==QColor("#628ed1")&&loaded.horizonOpacity==70&&loaded.horizonWidth==1,"DRW must restore perspective geometry and locks without stored appearance");
        QZipReader styledArchive(out.filePath("styled-guides.drw"));const auto styledMetadata=QJsonDocument::fromJson(styledArchive.fileData("project.json")).object();const auto storedPerspective=styledMetadata.value("perspective").toObject();
        const auto storedPoint=storedPerspective.value("points").toArray().first().toObject();require(styledMetadata.value("version").toInt()==5&&storedPoint.value("locked").toBool()&&storedPerspective.value("horizon").toObject().value("locked").toBool(),"DRW must contain the vanishing-point collection and perspective locks");
        Canvas styledCanvas;styled.image=QImage(200,200,QImage::Format_ARGB32_Premultiplied);styled.image.fill(Qt::white);styled.vanishingPoints[0].position=QPointF(100,100);styled.horizonY=100;styled.rayStepDegrees=30;styled.rayGap=20;styled.rayStartOpacity=10;styled.rayEndOpacity=70;styled.rayFadeLength=50;styledCanvas.resize(400,400);styledCanvas.setDocument(styled);
        QImage styledView(styledCanvas.size(),QImage::Format_ARGB32_Premultiplied);styledView.fill(Qt::transparent);styledCanvas.render(&styledView);const QPointF styledVanishing=styledCanvas.toView(styled.vanishingPoints[0].position);
        const QColor gapPixel=styledView.pixelColor(qRound(styledVanishing.x()),qRound(styledVanishing.y()+12));const QColor startPixel=styledView.pixelColor(qRound(styledVanishing.x()),qRound(styledVanishing.y()+22));const QColor endPixel=styledView.pixelColor(qRound(styledVanishing.x()),qRound(styledVanishing.y()+80));
        auto darkness=[](const QColor &color){return 765-color.red()-color.green()-color.blue();};require(gapPixel==QColor(Qt::white)&&darkness(endPixel)>darkness(startPixel),"perspective ray gap or opacity ramp was not rendered");
        const QRectF styledPaper(styledCanvas.toView(QPointF()),QSizeF(styled.image.size())*styledCanvas.zoom());
        const QColor independentHorizon=styledView.pixelColor(qRound(styledPaper.right()+20),qRound(styledCanvas.toView(QPointF(0,styled.horizonY)).y()));require(independentHorizon==styled.horizonColor,"horizon must use its own color, opacity, and line width");
        require(styledView.pixelColor(qRound(styledVanishing.x()),qRound(styledPaper.bottom()+12))==QColor("#dce0e5"),"perspective ray must stop after crossing the canvas");
        DrawingState outside=styled;outside.vanishingPoints[0].position=QPointF(-50,0);outside.horizonY=0;outside.rayStepDegrees=30;outside.rayGap=0;outside.rayStartOpacity=100;outside.rayEndOpacity=100;outside.rayFadeLength=0;styledCanvas.setDocument(outside);
        QImage filteredView(styledCanvas.size(),QImage::Format_ARGB32_Premultiplied);filteredView.fill(Qt::transparent);styledCanvas.render(&filteredView);const QPointF outsideVanishing=styledCanvas.toView(outside.vanishingPoints[0].position);
        auto hasGuidePixel=[&](QPointF point){for(int y=qRound(point.y())-2;y<=qRound(point.y())+2;++y)for(int x=qRound(point.x())-2;x<=qRound(point.x())+2;++x)if(filteredView.valid(x,y)&&filteredView.pixelColor(x,y)!=QColor("#dce0e5"))return true;return false;};
        require(hasGuidePixel(outsideVanishing+QPointF(52,30))&&!hasGuidePixel(outsideVanishing+QPointF(0,50))&&!hasGuidePixel(outsideVanishing+QPointF(260,150)),"perspective rays must approach and cross the canvas, stop at its far edge, and hide when they miss it");
        QSettings applicationAppearance;applicationAppearance.setValue("perspective/common/rayStepDegrees",6.5);applicationAppearance.setValue("perspective/common/rayGap",18);applicationAppearance.setValue("perspective/common/rayStartOpacity",16);applicationAppearance.setValue("perspective/common/rayEndOpacity",76);applicationAppearance.setValue("perspective/common/rayFadeLength",56);
        MainWindow pathWindow;require(pathWindow.openPath(projectPath),"path settings fixture did not open");
        require(pathWindow.canvas()->state().vanishingPoints==canvas->state().vanishingPoints&&pathWindow.canvas()->state().horizonY==canvas->state().horizonY&&pathWindow.canvas()->state().rayStepDegrees==6.5&&pathWindow.canvas()->state().rayGap==18&&pathWindow.canvas()->state().rayStartOpacity==16&&pathWindow.canvas()->state().rayEndOpacity==76&&pathWindow.canvas()->state().rayFadeLength==56,"opening DRW must combine project geometry with application appearance settings");
        require(QDir(QSettings().value("files/openDirectory").toString())==QDir(out.absolutePath())&&!QSettings().contains("files/saveDirectory"),"open and save directories must be independent");
        auto *pathSaveAction=pathWindow.findChild<QAction*>("saveAction");require(pathSaveAction,"save action missing");pathSaveAction->trigger();QApplication::processEvents();
        require(QDir(QSettings().value("files/saveDirectory").toString())==QDir(out.absolutePath()),"successful save did not remember its directory");pathWindow.close();QSettings().remove("perspective/common");
        QStringList recentPaths;for(int i=0;i<6;++i){const QString path=out.filePath(QString("recent-%1.drw").arg(i));require(Project::save(path,loaded,&error),qPrintable(error));recentPaths.append(QFileInfo(path).absoluteFilePath());}
        MainWindow recentWindow;for(const auto &path:recentPaths)require(recentWindow.openPath(path),"recent file fixture did not open");
        auto *recentMenu=recentWindow.findChild<QMenu*>("recentFilesMenu");require(recentMenu&&recentMenu->actions().size()==5,"recent files menu must contain five entries");
        const QStringList storedRecent=QSettings().value("files/recentFiles").toStringList();
        require(storedRecent.size()==5&&storedRecent.first()==recentPaths.last()&&!storedRecent.contains(recentPaths.first())&&recentMenu->actions().first()->data().toString()==recentPaths.last(),"recent files order, limit, or menu data is wrong");
        MainWindow persistedRecentWindow;auto *persistedRecentMenu=persistedRecentWindow.findChild<QMenu*>("recentFilesMenu");
        require(persistedRecentMenu&&persistedRecentMenu->actions().size()==5&&persistedRecentMenu->actions().first()->data().toString()==recentPaths.last(),"recent files did not persist between windows");recentWindow.close();persistedRecentWindow.close();
        MainWindow widthsWindow;auto *widthControl=widthsWindow.findChild<QSpinBox*>("strokeWidth");auto *pencilAction=widthsWindow.findChild<QAction*>("tool0");auto *brushAction=widthsWindow.findChild<QAction*>("tool1");auto *eraserAction=widthsWindow.findChild<QAction*>("tool2");auto *panAction=widthsWindow.findChild<QAction*>("tool3");
        require(widthControl&&pencilAction&&brushAction&&eraserAction&&panAction,"per-tool width controls are missing");
        widthControl->setValue(4);brushAction->trigger();require(widthControl->value()==3,"brush must start with its own width");widthControl->setValue(11);eraserAction->trigger();require(widthControl->value()==3,"eraser must start with its own width");widthControl->setValue(17);
        pencilAction->trigger();require(widthControl->value()==4,"pencil width was not restored");brushAction->trigger();require(widthControl->value()==11,"brush width was not restored");eraserAction->trigger();require(widthControl->value()==17,"eraser width was not restored");panAction->trigger();require(!widthControl->isEnabled(),"width control must be disabled for a non-paint tool");
        auto *widthDialogAction=widthsWindow.findChild<QAction*>("strokeWidthAction");bool widthDialogShown=false;QTimer::singleShot(0,&widthsWindow,[&]{auto *dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());auto *pencil=dialog?dialog->findChild<QSpinBox*>("pencilWidthSetting"):nullptr;auto *brush=dialog?dialog->findChild<QSpinBox*>("brushWidthSetting"):nullptr;auto *eraser=dialog?dialog->findChild<QSpinBox*>("eraserWidthSetting"):nullptr;widthDialogShown=dialog&&pencil&&brush&&eraser&&pencil->value()==4&&brush->value()==11&&eraser->value()==17;if(pencil)pencil->setValue(6);if(brush)brush->setValue(12);if(eraser)eraser->setValue(18);if(dialog)dialog->accept();});require(widthDialogAction,"stroke width menu action is missing");widthDialogAction->trigger();
        require(widthDialogShown&&QSettings().value("tools/pencilWidth").toInt()==6&&QSettings().value("tools/brushWidth").toInt()==12&&QSettings().value("tools/eraserWidth").toInt()==18&&!widthControl->isEnabled(),"stroke width menu did not work while a non-paint tool was active");pencilAction->trigger();require(widthControl->value()==6,"menu did not update pencil width");brushAction->trigger();require(widthControl->value()==12,"menu did not update brush width");eraserAction->trigger();require(widthControl->value()==18,"menu did not update eraser width");widthsWindow.close();
        MainWindow persistedWidthsWindow;widthControl=persistedWidthsWindow.findChild<QSpinBox*>("strokeWidth");brushAction=persistedWidthsWindow.findChild<QAction*>("tool1");eraserAction=persistedWidthsWindow.findChild<QAction*>("tool2");
        require(widthControl&&widthControl->value()==6,"pencil width did not persist");brushAction->trigger();require(widthControl->value()==12,"brush width did not persist");eraserAction->trigger();require(widthControl->value()==18,"eraser width did not persist");persistedWidthsWindow.close();
        require(Project::exportPng(out.filePath("export.png"),canvas->state().image,&error),qPrintable(error));QImage png;require(Project::loadPng(out.filePath("export.png"),&png,&error),qPrintable(error));require(png==pixels,"grid leaked into exported PNG");
        DrawingState transparent=loaded;transparent.image.fill(Qt::transparent);transparent.image.setPixelColor(7,8,QColor(40,80,120,128));require(Project::save(out.filePath("alpha.drw"),transparent,&error),qPrintable(error));require(Project::load(out.filePath("alpha.drw"),&loaded,&error),qPrintable(error));require(loaded.image==transparent.image,"alpha roundtrip failed");
        QFile bad(out.filePath("bad.drw"));bad.open(QIODevice::WriteOnly);bad.write("not a zip");bad.close();DrawingState unchanged=loaded;require(!Project::load(bad.fileName(),&loaded,&error),"bad project accepted");require(loaded.image==unchanged.image,"failed load modified destination");
        require(!Project::save(out.filePath("missing/fail.drw"),loaded,&error),"save to missing directory should fail");
        QZipWriter invalid(out.filePath("version.drw"));invalid.addFile("drawing.png",QByteArray("bad"));invalid.addFile("project.json",QByteArray("{\"format\":\"Drawing\",\"version\":99,\"image\":\"drawing.png\"}"));invalid.close();require(!Project::load(out.filePath("version.drw"),&loaded,&error),"unknown project version accepted");
        QByteArray legacyPng;QBuffer legacyBuffer(&legacyPng);legacyBuffer.open(QIODevice::WriteOnly);require(initial.image.save(&legacyBuffer,"PNG"),"legacy PNG encoding failed");
        QJsonObject legacyPerspective{{"visible",false},{"x",650.0},{"y",240.0},{"rays",16},{"color",QStringLiteral("#ff628ed1")}};
        QJsonObject legacyMetadata{{"format","Drawing"},{"version",1},{"width",1000},{"height",620},{"image","drawing.png"},{"perspective",legacyPerspective}};
        QZipWriter legacy(out.filePath("legacy-v1.drw"));legacy.addFile("drawing.png",legacyPng);legacy.addFile("project.json",QJsonDocument(legacyMetadata).toJson());legacy.close();
        DrawingHistory legacyHistory;require(Project::load(out.filePath("legacy-v1.drw"),&legacyHistory,&error)&&legacyHistory.states.size()==1&&legacyHistory.index==0&&legacyHistory.labels.isEmpty()&&legacyHistory.states.first().rayStepDegrees==10&&legacyHistory.states.first().horizonY==240,"version 1 project geometry compatibility failed");
        require(!Project::validSize(QSize(8192,8192))&&!Project::validSize(QSize(-1,10)),"invalid canvas size accepted");
        if(QGuiApplication::platformName()!="offscreen"){
        bool cancelClicked=false;
        QTimer::singleShot(0,&window,[&]{auto *box=qobject_cast<QMessageBox*>(QApplication::activeModalWidget());if(box){for(auto *button:box->buttons())if(button->text()==QStringLiteral("Отмена")){cancelClicked=true;button->click();return;}box->reject();}});
        require(!window.close()&&cancelClicked&&window.isVisible(),"cancel must prevent closing dirty document");
        canvas->undoStack()->setClean();
        require(window.openPath(projectPath)&&canvas->undoStack()->canUndo()&&canvas->undoStack()->canRedo(),"opening saved project did not restore history");
        canvas->setTool(Canvas::Pencil);drag(canvas,{40,40},{90,40});
        const QImage beforeFailedOpen=canvas->state().image;
        QTimer::singleShot(0,&window,[]{auto *box=qobject_cast<QMessageBox*>(QApplication::activeModalWidget());if(box)box->accept();});
        require(!window.openPath(bad.fileName())&&canvas->state().image==beforeFailedOpen&&!canvas->undoStack()->isClean(),"failed open must preserve dirty document");
        bool saveClicked=false;
        QTimer::singleShot(0,&window,[&]{auto *box=qobject_cast<QMessageBox*>(QApplication::activeModalWidget());if(box){for(auto *button:box->buttons())if(button->text()==QStringLiteral("Сохранить")){saveClicked=true;button->click();return;}box->reject();}});
        require(window.close()&&saveClicked,"save before closing failed");
        require(Project::load(projectPath,&loaded,&error)&&loaded.image==beforeFailedOpen,"save on close lost changes");
        require(Project::load(projectPath,&loadedHistory,&error)&&loadedHistory.index==loadedHistory.labels.size()&&loadedHistory.labels.size()>1,"save on close lost undo history or retained discarded redo branch");
        window.show();QApplication::processEvents();
        }
        canvas->setDocument(initial);canvas->setTool(Canvas::Pencil);canvas->setFront(QColor("#526070"));canvas->setStrokeWidth(2);canvas->fit();
        const QVector<QPointF> house{{230,450},{230,265},{400,173},{563,270},{563,451},{230,450}};
        for(int i=1;i<house.size();++i)drag(canvas,house[i-1],house[i]);
        drag(canvas,{230,265},{400,352});drag(canvas,{400,352},{563,270});drag(canvas,{400,173},{400,352});drag(canvas,{400,352},{563,451});drag(canvas,{442,380},{442,316});drag(canvas,{442,316},{488,294});drag(canvas,{488,294},{488,409});drag(canvas,{183,472},{600,472});
        require(Project::save(out.filePath("Набросок.drw"),canvas->state(),&error),qPrintable(error));
        QApplication::processEvents();require(window.grab().save(out.filePath("editor.png")),"screenshot failed");
        window.resize(720,480);QApplication::processEvents();require(window.grab().save(out.filePath("editor-small.png")),"small screenshot failed");window.resize(1200,800);QApplication::processEvents();
        auto *action=window.findChild<QAction*>("tool4");require(action,"perspective action missing");action->trigger();QApplication::processEvents();require(window.grab().save(out.filePath("perspective.png")),"perspective screenshot failed");
        canvas->undoStack()->setClean();window.close();
        QFile report(out.filePath("result.txt"));report.open(QIODevice::WriteOnly);report.write("PASS: pencil, brush, eraser, connected segments, angle constraint, persistent undo/redo history, DRW v1 compatibility, pan/zoom, perspective, DRW/PNG, alpha, invalid input, screenshots\n");
        report.write(QGuiApplication::platformName()=="offscreen"?"SKIP: native dialog tests (run with -platform windows)\n":"PASS: close cancel/save, failed open preserves document\n");
        return 0;
    }catch(const std::exception &error){qCritical()<<"SELF_TEST_FAILED:"<<error.what();return 1;}
}
